from pydna.dseqrecord import Dseqrecord
from pydna.assembly2 import gateway_assembly

attB1 = 'ACAACTTTGTACAAAAAAGCAGAAG'
attP1 = 'AAAATAATGATTTTATTTGACTGATAGTGACCTGTTCGTTGCAACAAATTGATGAGCAATGCTTTTTTATAATGCCAACTTTGTACAAAAAAGCTGAACGAGAAGCGTAAAATGATATAAATATCAATATATTAAATTAGATTTTGCATAAAAAACAGACTACATAATACTGTAAAACACAACATATCCAGTCACTATGAATCAACTACTTAGATGGTATTAGTGACCTGTA'

seq1 = Dseqrecord('aaa' + attB1 + 'ccc' + attP1)

products = gateway_assembly([seq1], 'BP', False, False, False)
print(products)
