[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = "Backend of ShareYourCloning, a web application to generate molecular cloning strategies in json format, and share them with others."
license = "MIT"
name = "shareyourcloning_backend"
version = "0.1.0"

[tool.poetry.dependencies]
beautifulsoup4 = "^4.11.1"
fastapi = "*"
python = "^3.10"
python-multipart = "*"
uvicorn = "*"
python-queen = "^1.1.0"
httpx = "^0.25.0"
pydna = "^5.2.0"

[tool.poetry.dev-dependencies]
autopep8 = "*"
flake8 = "*"
ipykernel = "*"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
