[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = "Backend of ShareYourCloning, a web application to generate molecular cloning strategies in json format, and share them with others."
license = "MIT"
name = "shareyourcloning_backend"
version = "0.1.0"

[tool.poetry.dependencies]
beautifulsoup4 = "^4.11.1"
fastapi = "*"
httpx = "^0.25.0"
python = "^3.10"
python-multipart = "*"
uvicorn = "*"
pydna = { git = "https://github.com/BjornFJohansson/pydna", rev = "issue_157" }
requests = "^2.31.0"
regex = "^2023.10.3"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.4"
flake8 = "^6.1.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"


[tool.poetry.group.ipython.dependencies]
ipython = "^8.20.0"
ipykernel = "^6.28.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
